### ISSUE TITLE
Práctica6Hilos-DiegoAlexisCarlosCruz

### ISSUE THREAD

**Issue by g00gle2401** [SistemasTecTlaxiaco/practica-de-hilos-g00gle2401#2]
[Practica 6_4US.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-hilos-g00gle2401/files/8448585/Practica.6_4US.pdf)

**Comment by Gregorio012** [comment]
Calificación 17

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
